name: Documentation
description: Report a documentation issue or suggest an improvement
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the documentation!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong or missing in the documentation?
      placeholder: Describe the issue or improvement
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where in the documentation is the issue?
      placeholder: e.g., README, CONTRIBUTING, command help text
    validations:
      required: false

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: How would you improve it?
    validations:
      required: false
